cd C:\outputVideo
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video0.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video1.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video2.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video3.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video4.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video5.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video6.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video7.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video8.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video9.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video10.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video11.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video12.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video13.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video14.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video15.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video16.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video17.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video18.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video19.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video20.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video21.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video22.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video23.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video24.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video25.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video26.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video27.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video28.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video29.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video30.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video31.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video32.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video33.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video34.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video35.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video36.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video37.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video38.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video39.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video40.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video41.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video42.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video43.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video44.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video45.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video46.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video47.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video48.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video49.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video50.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video51.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video52.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video53.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video54.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video55.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video56.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video57.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video58.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video59.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video60.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video61.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video62.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video63.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video64.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video65.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video66.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video67.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video68.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video69.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video70.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video71.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video72.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video73.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video74.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video75.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video76.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video77.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video78.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video79.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video80.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video81.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video82.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video83.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video84.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video85.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video86.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video87.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video88.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video89.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video90.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video91.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video92.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video93.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video94.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video95.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video96.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video97.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video98.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video99.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video100.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video101.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video102.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video103.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video104.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video105.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video106.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video107.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video108.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video109.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video110.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video111.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video112.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video113.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video114.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video115.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video116.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video117.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video118.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video119.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video120.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video121.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video122.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video123.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video124.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video125.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video126.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video127.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video128.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video129.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video130.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video131.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video132.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video133.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video134.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video135.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video136.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video137.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video138.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video139.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video140.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video141.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video142.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video143.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video144.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video145.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video146.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video147.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video148.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video149.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video150.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video151.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video152.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video153.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video154.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video155.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video156.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video157.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video158.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video159.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video160.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video161.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video162.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video163.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video164.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video165.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video166.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video167.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video168.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video169.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video170.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video171.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video172.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video173.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video174.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video175.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video176.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video177.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video178.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video179.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video180.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video181.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video182.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video183.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video184.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video185.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video186.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video187.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video188.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video189.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video190.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video191.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video192.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video193.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video194.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video195.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video196.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video197.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video198.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video199.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video200.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video201.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video202.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video203.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video204.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video205.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video206.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video207.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video208.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video209.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video210.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video211.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video212.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video213.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video214.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video215.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video216.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video217.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video218.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video219.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video220.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video221.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video222.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video223.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video224.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video225.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video226.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video227.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video228.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video229.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video230.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video231.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video232.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video233.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video234.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video235.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video236.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video237.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video238.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video239.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video240.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video241.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video242.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video243.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video244.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video245.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video246.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video247.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video248.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video249.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video250.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video251.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video252.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video253.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video254.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video255.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video256.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video257.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video258.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video259.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video260.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video261.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video262.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video263.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video264.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video265.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video266.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video267.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video268.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video269.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video270.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video271.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video272.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video273.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video274.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video275.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video276.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video277.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video278.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video279.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video280.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video281.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video282.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video283.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video284.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video285.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video286.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video287.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video288.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video289.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video290.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video291.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video292.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video293.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video294.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video295.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video296.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video297.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video298.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video299.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video300.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video301.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video302.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video303.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video304.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video305.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video306.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video307.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video308.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video309.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video310.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video311.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video312.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video313.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video314.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video315.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video316.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video317.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video318.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video319.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video320.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video321.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video322.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video323.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video324.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video325.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video326.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video327.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video328.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video329.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video330.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video331.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video332.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video333.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video334.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video335.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video336.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video337.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video338.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video339.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video340.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video341.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video342.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video343.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video344.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video345.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video346.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video347.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video348.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video349.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video350.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video351.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video352.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video353.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video354.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video355.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video356.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video357.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video358.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video359.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video360.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video361.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video362.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video363.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video364.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video365.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video366.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video367.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video368.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video369.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video370.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video371.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video372.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video373.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video374.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video375.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video376.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video377.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video378.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video379.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video380.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video381.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video382.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video383.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video384.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video385.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video386.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video387.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video388.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video389.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video390.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video391.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video392.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video393.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video394.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video395.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video396.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video397.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video398.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video399.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video400.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video401.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video402.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video403.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video404.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video405.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video406.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video407.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video408.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video409.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video410.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video411.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video412.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video413.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video414.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video415.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video416.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video417.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video418.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video419.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video420.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video421.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video422.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video423.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video424.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video425.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video426.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video427.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video428.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video429.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video430.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video431.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video432.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video433.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video434.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video435.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video436.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video437.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video438.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video439.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video440.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video441.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video442.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video443.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video444.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video445.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video446.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video447.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video448.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video449.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video450.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video451.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video452.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video453.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video454.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video455.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video456.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video457.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video458.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video459.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video460.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video461.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video462.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video463.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video464.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video465.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video466.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video467.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video468.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video469.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video470.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video471.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video472.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video473.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video474.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video475.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video476.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video477.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video478.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video479.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video480.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video481.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video482.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video483.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video484.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video485.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video486.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video487.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video488.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video489.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video490.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video491.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video492.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video493.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video494.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video495.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video496.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video497.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video498.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video499.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video500.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video501.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video502.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video503.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video504.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video505.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video506.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video507.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video508.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video509.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video510.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video511.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video512.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video513.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video514.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video515.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video516.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video517.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video518.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video519.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video520.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video521.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video522.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video523.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video524.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video525.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video526.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video527.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video528.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video529.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video530.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video531.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video532.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video533.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video534.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video535.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video536.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video537.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video538.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video539.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video540.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video541.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video542.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video543.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video544.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video545.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video546.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video547.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video548.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video549.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video550.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video551.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video552.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video553.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video554.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video555.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video556.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video557.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video558.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video559.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video560.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video561.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video562.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video563.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video564.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video565.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video566.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video567.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video568.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video569.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video570.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video571.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video572.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video573.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video574.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video575.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video576.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video577.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video578.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video579.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video580.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video581.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video582.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video583.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video584.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video585.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video586.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video587.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video588.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video589.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video590.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video591.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video592.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video593.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video594.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video595.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video596.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video597.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video598.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video599.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video600.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video601.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video602.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video603.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video604.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video605.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video606.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video607.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video608.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video609.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video610.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video611.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video612.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video613.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video614.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video615.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video616.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video617.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video618.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video619.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video620.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video621.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video622.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video623.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video624.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video625.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video626.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video627.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video628.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video629.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video630.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video631.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video632.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video633.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video634.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video635.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video636.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video637.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video638.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video639.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video640.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video641.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video642.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video643.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video644.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video645.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video646.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video647.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video648.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video649.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video650.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video651.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video652.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video653.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video654.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video655.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video656.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video657.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video658.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video659.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video660.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video661.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video662.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video663.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video664.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video665.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video666.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video667.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video668.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video669.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video670.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video671.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video672.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video673.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video674.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video675.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video676.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video677.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video678.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video679.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video680.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video681.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video682.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video683.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video684.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video685.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video686.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video687.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video688.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video689.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video690.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video691.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video692.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video693.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video694.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video695.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video696.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video697.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video698.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video699.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video700.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video701.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video702.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video703.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video704.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video705.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video706.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video707.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video708.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video709.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video710.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video711.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video712.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video713.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video714.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video715.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video716.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video717.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video718.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video719.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video720.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video721.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video722.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video723.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video724.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video725.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video726.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video727.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video728.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video729.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video730.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video731.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video732.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video733.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video734.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video735.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video736.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video737.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video738.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video739.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video740.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video741.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video742.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video743.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video744.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video745.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video746.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video747.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video748.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video749.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video750.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video751.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video752.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video753.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video754.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video755.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video756.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video757.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video758.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video759.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video760.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video761.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video762.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video763.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video764.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video765.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video766.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video767.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video768.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video769.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video770.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video771.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video772.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video773.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video774.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video775.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video776.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video777.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video778.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video779.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video780.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video781.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video782.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video783.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video784.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video785.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video786.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video787.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video788.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video789.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video790.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video791.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video792.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video793.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video794.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video795.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video796.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video797.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video798.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video799.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video800.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video801.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video802.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video803.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video804.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video805.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video806.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video807.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video808.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video809.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video810.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video811.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video812.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video813.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video814.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video815.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video816.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video817.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video818.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video819.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video820.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video821.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video822.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video823.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video824.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video825.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video826.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video827.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video828.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video829.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video830.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video831.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video832.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video833.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video834.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video835.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video836.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video837.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video838.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video839.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video840.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video841.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video842.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video843.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video844.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video845.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video846.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video847.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video848.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video849.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video850.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video851.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video852.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video853.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video854.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video855.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video856.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video857.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video858.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video859.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video860.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video861.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video862.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video863.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video864.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video865.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video866.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video867.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video868.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video869.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video870.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video871.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video872.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video873.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video874.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video875.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video876.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video877.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video878.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video879.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video880.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video881.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video882.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video883.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video884.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video885.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video886.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video887.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video888.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video889.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video890.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video891.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video892.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video893.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video894.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video895.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video896.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video897.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video898.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video899.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video900.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video901.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video902.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video903.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video904.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video905.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video906.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video907.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video908.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video909.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video910.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video911.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video912.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video913.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video914.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video915.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video916.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video917.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video918.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video919.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video920.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video921.png
texconv -f DXT1 -o "C:\\outputVideo\\dds2" -nologo video922.png
